### ISSUE TITLE
ffmpeg not found in $PATH

### ISSUE THREAD

**Issue by rumkin** [cellofellow/ffmpeg#5]
Running container with script below causing error 

```
"ffmpeg": executable file not found in $PATH.
```

Command:

``` shell
docker run --rm -v $PWD:/data \
    -w /data \
    cellofellow/ffmpeg \
    ffmpeg -i test.caf test.mp3
```

**Comment by cellofellow** [comment]
Yeah, last I was messing with this ffmpeg was actually failing to compile, but that wasn't causing the build to fail for some reason.

**Comment by 1o0ko** [comment]
^ Up, is this going to be solved per any chance?

**Comment by cellofellow** [comment]
I pushed a new version a couple of days ago. It's fixed.
