### ISSUE TITLE
Container usage

### ISSUE THREAD

**Issue by sebzimmermann** [cellofellow/ffmpeg#8]
Hi,
could you maybe add some description to the README (e.g. examples) on how to use this image? I'm kind of lost here...

```
docker run --rm -v $PWD:/test -w /data cellofellow/ffmpeg ffmpeg -version
docker: Error response from daemon: Container command 'ffmpeg' not found or does not exist..
```

**Comment by ringwald** [comment]
It already defaults to running ffmpeg, so you don't have to use that. Your command should look like: 
docker run --rm -v $PWD:/test -w /data cellofellow/ffmpeg  -version
